// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Repository struct {
	ID        int64              `json:"id"`
	GithubID  int64              `json:"github_id"`
	UserID    int64              `json:"user_id"`
	FullName  string             `json:"full_name"`
	Owner     string             `json:"owner"`
	Name      string             `json:"name"`
	IsActive  *bool              `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          int64              `json:"id"`
	GithubID    int64              `json:"github_id"`
	Username    string             `json:"username"`
	Email       *string            `json:"email"`
	AvatarUrl   *string            `json:"avatar_url"`
	AccessToken *string            `json:"access_token"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
