// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRepository(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetRepositoryByFullName(ctx context.Context, fullName string) (Repository, error)
	GetRepositoryByGithubID(ctx context.Context, githubID int64) (Repository, error)
	GetRepositoryByID(ctx context.Context, id int64) (Repository, error)
	GetUserByGithubID(ctx context.Context, githubID int64) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListActiveRepositories(ctx context.Context) ([]Repository, error)
	ListRepositoriesByUser(ctx context.Context, userID int64) ([]Repository, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateRepositoryStatus(ctx context.Context, arg UpdateRepositoryStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserToken(ctx context.Context, arg UpdateUserTokenParams) error
}

var _ Querier = (*Queries)(nil)
