// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountCommentsByPR(ctx context.Context, prID int64) (int64, error)
	CountUnpostedComments(ctx context.Context, prID int64) (int64, error)
	CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) (PullRequest, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	CreateReviewComment(ctx context.Context, arg CreateReviewCommentParams) (ReviewComment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePullRequest(ctx context.Context, id int64) error
	DeleteRepository(ctx context.Context, id int64) error
	DeleteReviewComment(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetPullRequestByGithubID(ctx context.Context, githubID int64) (PullRequest, error)
	GetPullRequestByID(ctx context.Context, id int64) (PullRequest, error)
	GetPullRequestByRepoAndNumber(ctx context.Context, arg GetPullRequestByRepoAndNumberParams) (PullRequest, error)
	GetRepositoryByFullName(ctx context.Context, fullName string) (Repository, error)
	GetRepositoryByGithubID(ctx context.Context, githubID int64) (Repository, error)
	GetRepositoryByID(ctx context.Context, id int64) (Repository, error)
	GetReviewCommentByID(ctx context.Context, id int64) (ReviewComment, error)
	GetUserByGithubID(ctx context.Context, githubID int64) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListActiveRepositories(ctx context.Context) ([]Repository, error)
	ListPullRequestsByRepository(ctx context.Context, arg ListPullRequestsByRepositoryParams) ([]PullRequest, error)
	ListRepositoriesByUser(ctx context.Context, userID int64) ([]Repository, error)
	ListReviewCommentsByPR(ctx context.Context, prID int64) ([]ReviewComment, error)
	ListUnpostedComments(ctx context.Context, prID int64) ([]ReviewComment, error)
	ListUnreviewedPullRequests(ctx context.Context, repositoryID int64) ([]PullRequest, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkCommentAsPosted(ctx context.Context, arg MarkCommentAsPostedParams) error
	MarkPullRequestReviewed(ctx context.Context, id int64) error
	UpdatePullRequestStatus(ctx context.Context, arg UpdatePullRequestStatusParams) error
	UpdateRepositoryStatus(ctx context.Context, arg UpdateRepositoryStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserToken(ctx context.Context, arg UpdateUserTokenParams) error
}

var _ Querier = (*Queries)(nil)
